{% set name = "striprtf" %}
{% set version = "0.0.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/striprtf-{{ version }}.tar.gz
  sha256: 5a822d075e17417934ed3add6fc79b5fc8fb544fe4370b2f894cdd28f0ddd78e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
  run:
    - python >=3.9

test:
  imports:
    - striprtf
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/joshy/striprtf
  summary: A simple library to convert rtf to text
  description: |
    striprtf is a simple library to convert rtf to text. It is meant for
    extracting text from RTF files, particularly medical documents, into
    plain text for easier parsing.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/joshy/striprtf

extra:
  recipe-maintainers:
    - jan-janssen
